layout_spectrum: 0.5071453353122688
typography_spectrum: 0.783335466661426
color:
  brandStrength: 0.726455389743597
  lightness: 0.7126539795096078
  saturation: 0.6147289226665208
  rhythmicContrast: 0.740503688783265
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
github: true
analytics:
  google: UA-634542-84
author:
  name: ''
  email: ''
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ac9845c9-407c-42c0-96a0-6fe22929dffe.png
name: elenaberlo.com
url: 'http://elenaberlo.com'
navigation:
  - name: Say Hello
    id: b31709fa-ce91-4dce-a7ed-30c61964a56b
    type: content
  - name: Modern Ketubah
    url: 'https://www.onceuponapaper.net/pages/ketubah'
    type: external
  - name: Watercolor Paintings
    url: 'https://www.onceuponapaper.net/collections/watercolor-paintings'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f21a7e48-2b99-4950-9b08-6eadc760f4c5.png
title: Elena Berlo
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/64d365bd-3b57-4aac-9710-9c01fa9ca28e.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/64d365bd-3b57-4aac-9710-9c01fa9ca28e.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Modern Ketubah & Watercolor Paintings
purpose:
  - type: contact
    url: 'mailto:commission@elenaberlo.com'
    label: convo me for a commission
  - type: external
    url: 'https://www.onceuponapaper.net/'
    label: visit my shop @OnceUponaPaper
